/**
 * Generated by einblick-sdk on 2026-07-23T12:47:53.272Z.
 * Schema source: openapi-endpoint.
 * Do not edit manually.
 */

import { createEinblickClient } from '@einblick/sdk'
import type {
  CreateEinblickClientOptions,
  EinblickClient,
  EinblickAsset,
  EinblickResourceFields,
} from '@einblick/sdk'

export type EinblickSchema = {
  infos: {
    name: "Infos"
    mode: "singleton"
    sourceType: "cms"
    fields: {
      email?: string
      website?: string
      instagram?: string
    }
  }
  members: {
    name: "Members"
    mode: "collection"
    sourceType: "cms"
    fields: {
      name: string
      title: string
      description: string
      email: string
      website?: string
      instagram?: string
      image?: EinblickAsset | null
      projects?: unknown
    }
  }
  posts: {
    name: "Posts"
    mode: "collection"
    sourceType: "cms"
    fields: {
      title: string
      description: string
      content: string
      kind: "event" | "space" | "project"
      pinned?: boolean
      published_at: string
      date_labels?: Array<string>
      location_label?: string
      image?: EinblickAsset | null
      images?: EinblickAsset[]
      tags?: Array<string>
    }
  }
}

export type EinblickResourceSlug = keyof EinblickSchema

export type InfosFields = EinblickResourceFields<EinblickSchema, "infos">
export type MembersFields = EinblickResourceFields<EinblickSchema, "members">
export type PostsFields = EinblickResourceFields<EinblickSchema, "posts">

export type InfosWritableFields = Record<string, never>
export type MembersWritableFields = Record<string, never>
export type PostsWritableFields = Record<string, never>

type BaseEinblickClient = EinblickClient<EinblickSchema>

export type GeneratedEinblickResourceClients = {
  [key: string]: never
}

type GeneratedEinblickResourceClientMixin = {
  readonly resources: GeneratedEinblickResourceClients
}

export type GeneratedEinblickClient = BaseEinblickClient & GeneratedEinblickResourceClientMixin

function createGeneratedResourceClients(): GeneratedEinblickResourceClients {
  return {} as GeneratedEinblickResourceClients
}

export const RESOURCE_SOURCE_TYPES = {
  infos: "cms",
  members: "cms",
  posts: "cms",
} as const satisfies Record<EinblickResourceSlug, "cms" | "native">

export function createGeneratedEinblickClient(
  options: Partial<CreateEinblickClientOptions> = {}
): GeneratedEinblickClient {
  const client = createEinblickClient<EinblickSchema>({
    ...options,
    resourceSourceTypes: { ...RESOURCE_SOURCE_TYPES, ...options.resourceSourceTypes },
  })

  return Object.assign(client, {
    resources: createGeneratedResourceClients(),
  }) as GeneratedEinblickClient
}

export const createEinblick = createGeneratedEinblickClient
