/**
 * Generated by einblick-sdk on 2026-04-29T08:06:32.783Z.
 * Schema source: openapi-endpoint.
 * Do not edit manually.
 */

import { createEinblickClient } from '@einblick/sdk'
import type {
  CreateEinblickClientOptions,
  EinblickAsset,
  EinblickResourceFields,
} from '@einblick/sdk'

export type EinblickSchema = {
  infos: {
    name: "Infos"
    mode: "singleton"
    sourceType: "cms"
    fields: {
      email?: string
      website?: string
      instagram?: string
    }
  }
  members: {
    name: "Members"
    mode: "collection"
    sourceType: "cms"
    fields: {
      name: string
      title: string
      description: string
      email: string
      website?: string
      instagram?: string
      image?: EinblickAsset | null
      projects?: unknown
    }
  }
  posts: {
    name: "Posts"
    mode: "collection"
    sourceType: "cms"
    fields: {
      title: string
      description: string
      content: string
      kind: "event" | "space" | "project"
      pinned?: boolean
      published_at: string
      date_labels?: Array<string>
      location_label?: string
      image?: EinblickAsset | null
      images?: EinblickAsset[]
      tags?: Array<string>
    }
  }
}

export type EinblickResourceSlug = keyof EinblickSchema

export type InfosFields = EinblickResourceFields<EinblickSchema, "infos">
export type MembersFields = EinblickResourceFields<EinblickSchema, "members">
export type PostsFields = EinblickResourceFields<EinblickSchema, "posts">

export const RESOURCE_SOURCE_TYPES = {
  infos: "cms",
  members: "cms",
  posts: "cms",
} as const satisfies Record<EinblickResourceSlug, "cms" | "native">

export function createGeneratedEinblickClient(
  options: Partial<CreateEinblickClientOptions> = {}
) {
  return createEinblickClient<EinblickSchema>({
    ...options,
    resourceSourceTypes: { ...RESOURCE_SOURCE_TYPES, ...options.resourceSourceTypes },
  })
}

export const createEinblick = createGeneratedEinblickClient
